### ISSUE TITLE
ReferenceError: Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by maxalmonte14** [nguyenvanduocit/vue-loading-spinner#10]
I install the plugin without any problem, but when I try to use it in my project, console throws me the following error:

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in...

I'm doing like this:

import {CubeSpin} from 'vue-loading-spinner';
Vue.use(CubeSpin);

**Comment by nguyenvanduocit** [comment]
In your case, please try to install transform-runtime:
`yarn add babel-plugin-transform-runtime`
and go on if you miss any packages.
