### ISSUE TITLE
Parse error on 'import' when used within a component-based project

### ISSUE THREAD

**Issue by MellowCobra** [nguyenvanduocit/vue-loading-spinner#11]
Getting the following error when attempting to use in a component-based project with a Vueify build process:
```
/path/to/project/node_modules/vue-loading-spinner/src/index.js:1
import Circle from './components/Circle.vue'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Imported in my project's main.js like so:
```javascript
import {Hexagon} from 'vue-loading-spinner'
Vue.component('hexagon-loading-spinner', Hexagon)
```

**Comment by MellowCobra** [comment]
I believe this to be a problem with the way the project is importing vue components into the index.js file, as described by @LinusBorg in this [https://github.com/vuejs/vueify/issues/108](issue)

**Comment by jverce** [comment]
@MellowCobra were you able to troubleshoot this?

**Comment by gabel** [comment]
@jverce The only way to workaround was to use the spinner direct from the component.

Example:
```typescript
  import Plane from 'vue-loading-spinner/src/components/Plane.vue'
```

**Comment by MellowCobra** [comment]
I didn't continue troubleshooting much after this, but it seems like @gabel's solution could be a good workaround.
