### ISSUE TITLE
What license is this code released under?

### ISSUE THREAD

**Issue by dflock** [nguyenvanduocit/vue-loading-spinner#18]
Things that you create and don't specify a license for, are automatically copyrighted to you - and not re-usable by others without explicit permission.

As far as I can see, there's no license specified for this repository, so anyone who wants to use it would need to get permission directly from you for each use.

Is this intentional? If not, you should specify the license, so others can use it.

**Comment by jsonisathing** [comment]
Could we please get a follow up to this question?

**Comment by Katherraptor** [comment]
Also interested in a resolution to this question
