### ISSUE TITLE
This dependency was not found in node_modules

### ISSUE THREAD

**Issue by jersobh** [nguyenvanduocit/vue-loading-spinner#2]
Hi there,

I'm getting this error. Offcourse, installed with --save option;

 ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* vue-loading-spinner/components/Cube

Did you forget to run npm install --save for it?
> Listening at http://localhost:8080

**Comment by nguyenvanduocit** [comment]
Hi.
Try:
```
import {Cube} from 'vue-loading-spinner'
```
