### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by financialswprogrammer** [nguyenvanduocit/vue-loading-spinner#20]
I am seeing the following, any suggestions for what I might be doing wrong? 

Thank you

WARNING in ./src/main.js
13:8-16 "export 'CubeSpin' was not found in 'vue-loading-spinner'
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by nguyenvanduocit** [comment]
Sorry financialswprogrammer.

You can just copy the code of from file CubeSpin to your project.

I am rewriting it.

Thank you very much.
