### ISSUE TITLE
HourGlass: change color

### ISSUE THREAD

**Issue by nelhop** [nguyenvanduocit/vue-loading-spinner#22]
How can the color of 'HourGlass' be changed?

'<HourGlass background="#0002ab"></HourGlass>' seems not to be working.

**Comment by saleem-hadad** [comment]
Unfortunately, you can't change it, the source file shows the only property you can change is the size.

**Comment by webhacking** [comment]
There is one way..

But I don't want to recommend it. you can using css `important` property.
