### ISSUE TITLE
error:To install it, you can run: npm install --save vue-loading-spinner/components/Cube

### ISSUE THREAD

**Issue by WenTao-Love** [nguyenvanduocit/vue-loading-spinner#3]
in my project -- App.vue
`<template>
  <div id="app">
    <cube-spin></cube-spin>
    <keep-alive>
      <router-view></router-view>
    </keep-alive>
  </div>
</template>

<script>
  import CubeSpin from 'vue-loading-spinner/components/Cube'

  export default {
    data () {
      return {}
    },
    components: {
      CubeSpin
    }
  }
</script>`

**Comment by WenTao-Love** [comment]
the version:1.0.7

**Comment by nguyenvanduocit** [comment]
import {CubeSpin} from 'vue-loading-spinner'

**Comment by HotWordland** [comment]
@nguyenvanduocit 
```
import {CubeSpin} from 'vue-loading-spinner'
```
 not work still say 'Error: Can't resolve 'vue-loading-spinner' xxx Module not found '

**Comment by HotWordland** [comment]
sorry after i execute
```
npm install --save vue-loading-spinner
```
and i compile get error that 'Module build fail xxx Can't resolve scss-loader xxx'
fix it with add line to webpack.config.js file 
```
{
    test: /\.vue$/,
    loader: 'vue-loader',
    options: {
        loaders: {
            scss: 'style-loader!css-loader!sass-loader',
            sass: 'style-loader!css-loader!sass-loader?indentedSyntax',
        },
    },
},
```

**Comment by nguyenvanduocit** [comment]
Does everything ok for you?

**Comment by HotWordland** [comment]
@nguyenvanduocit yes thanks your contribution ~ 😄

**Comment by kodekrendel** [comment]
Got the same error, but this this workaround didnt help.

**Comment by donPuerto** [comment]
i have that error too, what i did copy the core and link to the page...

**Comment by npilipovic86** [comment]
I have this problem, and i fix this:

`App.vue
import Socket from 'vue-loading-spinner/src/components/Socket.vue'
@Component({
  components: {
    Socket
  }
})`
