### ISSUE TITLE
Isn't this managed anymore?

### ISSUE THREAD

**Issue by Jungwoo-An** [nguyenvanduocit/vue-loading-spinner#31]
@nguyenvanduocit 

is repo still maintaining? If not managed, i want to fork.

**Comment by irufus** [comment]
Not upgraded in 2 years.

**Comment by zhanghaifei1997** [comment]
Is there any development document?
I want to use it in my own project, but I find it doesn't work. I want to add this loading effect when the pop-up window appears.
