### ISSUE TITLE
License and coreui relationship

### ISSUE THREAD

**Issue by 3rd** [nguyenvanduocit/vue-loading-spinner#33]
Seeing that you have recent activity, I can only assume you are alive and well, and just a bad maintainer. There are multiple issues about adding a license to this snippet collection of spinners, issues that you've ignored.

About the **CubeGrid** spinner:
I'm not interested in that, but I'm interested in knowing if the spinners have been extracted from coreui (https://coreui.io/docs/2.1/components/spinners/) or not / or if they (ha ha) got them from you?

Thank you.

Addon: maintainers of open-source projects do not have an obligation to use their time on supporting the micro communities they're building, but not responding to multiple license inquires is a plain insult to this field of work we're in.

**Comment by zhanghaifei1997** [comment]
Is there any development document?
I want to use it in my own project, but I find it doesn't work. I want to add this loading effect when the pop-up window appears.

**Comment by nguyenvanduocit** [comment]
CoreUI using SpinKit. I used some spinner from SpinKit too. I'm going back to work on the project.
