### ISSUE TITLE
Error in parsing SVG: Unbound namespace prefix: "v-bind"

### ISSUE THREAD

**Issue by wlfnkls** [nguyenvanduocit/vue-loading-spinner#37]
Hey guys,

I know, this repo is not maintained anymore, but maybe you can help me anyways.

I built a vue.js app with parcel bundler in which im using this vue-loading-spinner component.
When I run `npm run build` I get this error in console:
`node_modules/vue-loading-spinner/src/components/Circle.vue: Error in parsing SVG: Unbound namespace prefix: "v-bind"
Line: 0
Column: 157
Char: >`

Maybe you have any idea where this is coming from, thank you!

**Comment by westongb** [comment]
Hey @wlfnkls did you ever find a solution to this? I am experiencing the same issue myself.

**Comment by wlfnkls** [comment]
Hey @westongb,

Im not sure what did the trick.

I just checked my git history and found this commit:
**Workaorung to avoid SVGO error on minifying** -> Add flagg  `--no-minify` to my build script in `package.json`

I hope this helps.
